name: Publish to PyPI

on:
  push:
    tags: ["v*.*.*"]      # tag like  v0.0.1  to publish

permissions:
  contents: read
  id-token: write         # 🟢 enables OIDC for PyPI

jobs:
  build-and-publish:
    environment: pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build sdist & wheel
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: dist     # default; just explicit
          skip_existing: true    # don’t fail if tag was re-run
