name: Publish to PyPI

on:
  push:
    tags: ["v*.*.*"]          # fires on v0.0.3, v1.2.0, etc.

permissions:
  contents: read
  id-token: write             # ← required for PyPI OIDC

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]   # runners for each platform
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # ---------- macOS: install libomp -----------------
      - name: Install libomp (macOS only)
        if: matrix.os == 'macos-latest'
        run: brew install libomp
      
      # ---------- build wheels --------------------------
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.1
        with:
          output-dir: wheelhouse
        env:
          # clang needs these flags to use Homebrew’s libomp
          CIBW_ENVIRONMENT_MACOS: |
            CFLAGS="-O3 -march=native -funroll-loops -ffast-math -fPIC -I/opt/homebrew/opt/libomp/include -Xpreprocessor -fopenmp"
            LDFLAGS="-L/opt/homebrew/opt/libomp/lib -lomp"
          CIBW_SKIP: "pp* *musllinux* *-win32 *win_amd64"

      # Linux job also builds an sdist once:
      - name: Build sdist
        if: matrix.os == 'ubuntu-latest'
        run: python -m pip install build && python -m build --sdist -o wheelhouse

      # ---------- publish --------------------------------
      - name: Publish wheels & sdist to PyPI
        if: matrix.os == 'ubuntu-latest'          # ← publish only from Linux
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse
          skip-existing: true


